project:
  type: website
  output-dir: _site

website:
  title: "深層学習ノート"
  description: "この個人ブログは深層学習について学んだことをまとめています。"
  site-url: https://akitsuyoshi.github.io/
  repo-url: https://github.com/Akitsuyoshi/Akitsuyoshi.github.io.git
  navbar:
    right:
      - icon: github
        href: https://github.com/Akitsuyoshi
format:
  html:
    light: simplex
    dark: darkly
    css: styles.css
    code-copy: true



